### ISSUE TITLE
0.4.0 checklist

### ISSUE THREAD

**Issue by beardedeagle** [beardedeagle/mnesiac#53]
1. Required
   * [ ] typespec everything
   * [ ] use structs throughout lib
   * [ ] drop config dir and files
   * [ ] convert `resolve_conflict/1` to hook for `amalgamate` netspit lib or remove entirely
   * [ ] doc everything
   * [ ] test coverage to 100%
   * [ ] expand distributed testing to cover more cases
2. Optional
   * [ ] add support for additional clustering libs, such as `partisan`
   * [ ] create hook for backing up mnesia tables
   * [ ] create hook for exodus migration lib

**Comment by beardedeagle** [comment]
The follow up plan to this release would be to cut a 1.0.0 if no complaints or bugs reported after month+ of internal/external use

**Comment by beardedeagle** [comment]
Effectively all that remains is converting the test suite to `local_cluster` and ensuring we hit 100% coverage, especially in regards to distributed testing.
